# Generated by Django 5.0.4 on 2024-04-05 15:16

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterPieces",
            fields=[
                ("song_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("Composer", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(default="songs/default.jpg", upload_to="songs/"),
                ),
                ("song", models.FileField(upload_to="songs/")),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
        ),
    ]
