# Generated by Django 5.0.4 on 2024-04-05 19:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0003_remove_masterpieces_composer"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Composers",
            new_name="Composer",
        ),
        migrations.RenameModel(
            old_name="MasterPieces",
            new_name="MasterPiece",
        ),
    ]
