# Generated by Django 5.0.4 on 2024-04-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0004_rename_composers_composer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="composer",
            name="genre",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
