# Generated by Django 5.0.4 on 2024-04-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0006_remove_masterpiece_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="composer",
            name="nationality",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
